dashscope/dashscope-sdk-java

- src/main/java/com/alibaba/dashscope/protocol/okhttp/OkHttpWebSocketClient.java
1. Remove test message as it will impact all websocket calls.
> fix: remove test message

- src/main/java/com/alibaba/dashscope/tools/ToolCallGsonDeserializer.java
fix: assistant call search stream exception
> fix: assistant call search stream exception

- pom.xml
> release: 2.16.10

- pom.xml
- src/main/java/com/alibaba/dashscope/Version.java
> release: 2.17.0

- src/main/java/com/alibaba/dashscope/audio/asr/recognition/timestamp/Sentence.java
Add emo_tag and emo_confidence in recognition sentence, will be supported in paraformer-realtime-8k-v2.
> [Add] emo tag and confidence in asr

- src/main/java/com/alibaba/dashscope/common/MessageAdapter.java
Use case #14 
Add null check for tool_calls
> [Enhance] Enhancing the robustness of tool_call judgments

- samples/VideoSynthesisUsage.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesis.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisListResult.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisOutput.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisParam.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisResult.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisUsage.java
- src/main/java/com/alibaba/dashscope/base/HalfDuplexParamBase.java
- src/main/java/com/alibaba/dashscope/base/HalfDuplexServiceParam.java
- src/main/java/com/alibaba/dashscope/utils/ApiKeywords.java
- src/main/java/com/alibaba/dashscope/utils/Constants.java
- src/test/java/com/alibaba/dashscope/TestVideoSynthesis.java
> Video synthesis

- src/main/java/com/alibaba/dashscope/audio/asr/recognition/Recognition.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/RecognitionResult.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/timestamp/Sentence.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/timestamp/Stash.java
- src/main/java/com/alibaba/dashscope/audio/asr/transcription/TranscriptionParam.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerApiKeywords.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerChat.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerParam.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerRealtime.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerState.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerUsage.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/Stash.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/TranscriptionResult.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/Translation.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/TranslationRecognizerResult.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/TranslationRecognizerResultPack.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/TranslationResult.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/results/Word.java
- src/main/java/com/alibaba/dashscope/audio/asr/vocabulary/Vocabulary.java
- src/main/java/com/alibaba/dashscope/audio/tts/SpeechSynthesizer.java
- src/main/java/com/alibaba/dashscope/audio/ttsv2/SpeechSynthesizer.java
- src/main/java/com/alibaba/dashscope/common/Function.java
- src/main/java/com/alibaba/dashscope/protocol/FullDuplexRequest.java
- src/main/java/com/alibaba/dashscope/protocol/HalfDuplexRequest.java
- src/test/java/com/alibaba/dashscope/TestTranslationRecognizer.java
- src/test/java/com/alibaba/dashscope/TestTranslationRecognizerChat.java
> Translation recognizer

- pom.xml
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisListResult.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisParam.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/Recognition.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/timestamp/Sentence.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerChat.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerRealtime.java
- src/main/java/com/alibaba/dashscope/audio/tts/SpeechSynthesizer.java
- src/main/java/com/alibaba/dashscope/audio/ttsv2/SpeechSynthesizer.java
- src/main/java/com/alibaba/dashscope/base/HalfDuplexServiceParam.java
- src/test/java/com/alibaba/dashscope/TestVideoSynthesis.java
1. reformat source code.
2. prepare for release v2.18.0
> release: prepare for release v2.18.0

- samples/MultiModalConversationUsage.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/AudioParameters.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationOutput.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationParam.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationUsage.java
- src/main/java/com/alibaba/dashscope/common/MultiModalMessage.java
- src/main/java/com/alibaba/dashscope/utils/ApiKeywords.java
1. add audio output modality.
2. add params for multimodel like max tokens, repeat penalty and presence penalty.
> feat: add audio output support

- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisUsage.java
fix VideoSynthesisUsage add video_duration and video_ratio
> fix VideoSynthesisUsage add video_duration and video_ratio

- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesisUsage.java
- src/main/java/com/alibaba/dashscope/common/Message.java
1. add reasoning_content response for DeepSeek model.
> feat: add reasoning_content response for DeepSeek model.

- pom.xml
> release: prepare release for v2.18.1

- pom.xml
1. fix reasoning_content result issue.
> release: prepare for release v2.18.2.

- samples/VideoSynthesisUsage.java
- src/main/java/com/alibaba/dashscope/aigc/videosynthesis/VideoSynthesis.java
fix VideoSynthesis class, using the list method to query the result is empty
> fix: return VideoSynthesisListResult instead of VideoSynthesisResult for listing video synthesis results.

- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationTokensDetails.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/OcrOptions.java
- src/main/java/com/alibaba/dashscope/common/ErrorType.java
- src/main/java/com/alibaba/dashscope/embeddings/MultiModalEmbedding.java
- src/main/java/com/alibaba/dashscope/embeddings/MultiModalEmbeddingResultItem.java
- src/main/java/com/alibaba/dashscope/exception/ApiException.java
- src/main/java/com/alibaba/dashscope/protocol/okhttp/OkHttpHttpClient.java
- src/main/java/com/alibaba/dashscope/utils/PreprocessMessageInput.java
1. add stack trace of error call of network issue.
2. reformat source codes.
> fix: add stack trace for error call of network issue

- pom.xml
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationTokensDetails.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/OcrOptions.java
- src/main/java/com/alibaba/dashscope/common/ErrorType.java
- src/main/java/com/alibaba/dashscope/embeddings/MultiModalEmbedding.java
- src/main/java/com/alibaba/dashscope/embeddings/MultiModalEmbeddingResultItem.java
- src/main/java/com/alibaba/dashscope/exception/ApiException.java
- src/main/java/com/alibaba/dashscope/protocol/okhttp/OkHttpHttpClient.java
- src/main/java/com/alibaba/dashscope/utils/PreprocessMessageInput.java
> release: release: prepare release for v2.18.5

- samples/MultiModelConversationQwenTts.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationParam.java
> fix: fix stream callback error

- samples/MultiModelConversationQvq.java
- src/main/java/com/alibaba/dashscope/aigc/multimodalconversation/MultiModalConversationResult.java
- src/main/java/com/alibaba/dashscope/common/MultiModalMessage.java
- src/main/java/com/alibaba/dashscope/common/MultiModalMessageAdapter.java
1. support reasoning content for multimodel call
> feat: support reasoning content for multimodel call

- src/main/java/com/alibaba/dashscope/audio/asr/recognition/Recognition.java
- src/main/java/com/alibaba/dashscope/audio/asr/recognition/timestamp/Sentence.java
- src/main/java/com/alibaba/dashscope/audio/asr/translation/TranslationRecognizerParam.java
- src/main/java/com/alibaba/dashscope/audio/asr/vocabulary/VocabularyService.java
- src/main/java/com/alibaba/dashscope/audio/ttsv2/enrollment/VoiceEnrollmentService.java
1. support heartbeat for recognition
2. support setting model for voice enrollment and asr vocabulary.
3. set default value for translation recognizer parameters
> feat: heartbeat for recognition and set model for enrollment, vocabulary

- samples/MultiModalDialogUsage.java
- src/main/java/com/alibaba/dashscope/base/FullDuplexParamBase.java
- src/main/java/com/alibaba/dashscope/multimodal/MultiModalDialog.java
- src/main/java/com/alibaba/dashscope/multimodal/MultiModalDialogApiKeyWords.java
- src/main/java/com/alibaba/dashscope/multimodal/MultiModalDialogCallback.java
- src/main/java/com/alibaba/dashscope/multimodal/MultiModalRequestParam.java
- src/main/java/com/alibaba/dashscope/multimodal/State.java
- src/main/java/com/alibaba/dashscope/protocol/FullDuplexRequest.java
- src/test/java/com/alibaba/dashscope/TestMultimodalDialog.java
Provide multimodal dialog API that supports text, images, voice, and video.
> [Add] Multimodal Dialog API

- src/main/java/com/alibaba/dashscope/protocol/okhttp/OkHttpWebSocketClient.java
enable reuse client after call close
> [Fix] enable reuse client after call close
